name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
      name: Push Docker Image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the repo
          uses: actions/checkout@v4
      
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USENAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: yvey7/calibre_web_dockerized:latest
            
